/* ============================================================
   QTERMINAL — markets-data.js
   The other 19 world indexes (NASDAQ-100/QQQ stays in data.js).

   SCOPE, READ THIS BEFORE TRUSTING A NUMBER:
   - Full real membership for indexes with a small, fixed roster:
     Dow 30, SENSEX, SMI, STI, IBEX 35, FTSE MIB, CAC 40, DAX,
     Euro Stoxx 50, Hang Seng.
   - MAJOR-CONSTITUENT SUBSET (not literally every name) for the
     large or "every stock on the exchange" indexes: S&P 500,
     FTSE 100, Nikkei 225, ASX 200, TSX Composite, Bovespa, Shanghai
     Composite, KOSPI, TAIEX. These cover the large majority of each
     index's actual market-cap weight (which is what shows up on a
     cap-sized heatmap anyway), but are NOT the complete roster —
     Shanghai/KOSPI/TAIEX in particular technically include
     thousands of listed stocks each; a literal full list isn't
     standard practice even on real terminals for these.
   - marketCapB is order-of-magnitude only, same caveat as data.js.
   - Local-exchange ticker codes (Hong Kong, Shanghai, Seoul,
     Singapore, Taipei) are lower-confidence than US/UK/EU ones —
     spot-check before relying on them for anything real.
   - `tokenized`: Robinhood only tokenizes US-listed stocks, so this
     is only meaningfully set for the two US markets here. Dow 30 is
     set true across the board (Robinhood's catalog is broad enough
     that all 30 blue chips are a safe bet); S&P 500 is true for the
     large majority with a deliberately-chosen minority left false
     for variety, same pattern as NASDAQ-100's own data. Every
     non-US market is tokenized:false throughout, per the "start
     with US markets" decision — flip these on a market's
     constituents once Robinhood actually tokenizes that market.
   ============================================================ */

const MARKETS = {};

MARKETS["DJI"] = {
  name: "Dow Jones Industrial Average",
  city: "New York",
  country: "USA",
  indexTicker: { ticker: "DIA", name: "SPDR Dow Jones Industrial Average ETF", sector: "Index", tokenized: true, marketCapB: 35 },
  constituents: [
  { ticker: "UNH", name: "UnitedHealth Group", sector: "Health Care", tokenized: true, marketCapB: 450 },
  { ticker: "GS", name: "Goldman Sachs Group", sector: "Financials", tokenized: true, marketCapB: 200 },
  { ticker: "MSFT", name: "Microsoft Corp.", sector: "Technology", tokenized: true, marketCapB: 3200 },
  { ticker: "HD", name: "Home Depot", sector: "Consumer Disc.", tokenized: true, marketCapB: 400 },
  { ticker: "CRM", name: "Salesforce Inc.", sector: "Technology", tokenized: true, marketCapB: 280 },
  { ticker: "CAT", name: "Caterpillar Inc.", sector: "Industrials", tokenized: true, marketCapB: 180 },
  { ticker: "AXP", name: "American Express", sector: "Financials", tokenized: true, marketCapB: 200 },
  { ticker: "V", name: "Visa Inc.", sector: "Financials", tokenized: true, marketCapB: 550 },
  { ticker: "AMGN", name: "Amgen Inc.", sector: "Health Care", tokenized: true, marketCapB: 160 },
  { ticker: "MCD", name: "McDonald's Corp.", sector: "Consumer Disc.", tokenized: true, marketCapB: 210 },
  { ticker: "BA", name: "Boeing Co.", sector: "Industrials", tokenized: true, marketCapB: 130 },
  { ticker: "HON", name: "Honeywell International", sector: "Industrials", tokenized: true, marketCapB: 140 },
  { ticker: "TRV", name: "Travelers Companies", sector: "Financials", tokenized: true, marketCapB: 55 },
  { ticker: "JPM", name: "JPMorgan Chase", sector: "Financials", tokenized: true, marketCapB: 600 },
  { ticker: "IBM", name: "IBM Corp.", sector: "Technology", tokenized: true, marketCapB: 200 },
  { ticker: "AAPL", name: "Apple Inc.", sector: "Technology", tokenized: true, marketCapB: 3400 },
  { ticker: "AMZN", name: "Amazon.com Inc.", sector: "Consumer Disc.", tokenized: true, marketCapB: 2000 },
  { ticker: "PG", name: "Procter & Gamble", sector: "Consumer Staples", tokenized: true, marketCapB: 380 },
  { ticker: "JNJ", name: "Johnson & Johnson", sector: "Health Care", tokenized: true, marketCapB: 380 },
  { ticker: "CVX", name: "Chevron Corp.", sector: "Energy", tokenized: true, marketCapB: 280 },
  { ticker: "MRK", name: "Merck & Co.", sector: "Health Care", tokenized: true, marketCapB: 250 },
  { ticker: "DIS", name: "Walt Disney Co.", sector: "Communication", tokenized: true, marketCapB: 200 },
  { ticker: "NKE", name: "Nike Inc.", sector: "Consumer Disc.", tokenized: true, marketCapB: 90 },
  { ticker: "WMT", name: "Walmart Inc.", sector: "Consumer Staples", tokenized: true, marketCapB: 700 },
  { ticker: "KO", name: "Coca-Cola Co.", sector: "Consumer Staples", tokenized: true, marketCapB: 280 },
  { ticker: "CSCO", name: "Cisco Systems", sector: "Technology", tokenized: true, marketCapB: 240 },
  { ticker: "VZ", name: "Verizon Communications", sector: "Communication", tokenized: true, marketCapB: 180 },
  { ticker: "MMM", name: "3M Co.", sector: "Industrials", tokenized: true, marketCapB: 80 },
  { ticker: "NVDA", name: "NVIDIA Corp.", sector: "Technology", tokenized: true, marketCapB: 3600 },
  { ticker: "SHW", name: "Sherwin-Williams", sector: "Materials", tokenized: true, marketCapB: 70 },
  ]
};

MARKETS["SPX"] = {
  name: "S&P 500",
  city: "New York",
  country: "USA",
  indexTicker: { ticker: "SPY", name: "SPDR S&P 500 ETF Trust", sector: "Index", tokenized: true, marketCapB: 550 },
  constituents: [
  { ticker: "AAPL", name: "Apple Inc.", sector: "Technology", tokenized: true, marketCapB: 3400 },
  { ticker: "MSFT", name: "Microsoft Corp.", sector: "Technology", tokenized: true, marketCapB: 3200 },
  { ticker: "NVDA", name: "NVIDIA Corp.", sector: "Technology", tokenized: true, marketCapB: 3600 },
  { ticker: "AMZN", name: "Amazon.com Inc.", sector: "Consumer Disc.", tokenized: true, marketCapB: 2000 },
  { ticker: "GOOGL", name: "Alphabet Inc. Class A", sector: "Communication", tokenized: true, marketCapB: 2200 },
  { ticker: "GOOG", name: "Alphabet Inc. Class C", sector: "Communication", tokenized: true, marketCapB: 2200 },
  { ticker: "META", name: "Meta Platforms Inc.", sector: "Communication", tokenized: true, marketCapB: 1500 },
  { ticker: "BRK.B", name: "Berkshire Hathaway", sector: "Financials", tokenized: true, marketCapB: 950 },
  { ticker: "AVGO", name: "Broadcom Inc.", sector: "Technology", tokenized: true, marketCapB: 1400 },
  { ticker: "TSLA", name: "Tesla Inc.", sector: "Consumer Disc.", tokenized: true, marketCapB: 1100 },
  { ticker: "JPM", name: "JPMorgan Chase", sector: "Financials", tokenized: true, marketCapB: 600 },
  { ticker: "WMT", name: "Walmart Inc.", sector: "Consumer Staples", tokenized: true, marketCapB: 700 },
  { ticker: "LLY", name: "Eli Lilly and Co.", sector: "Health Care", tokenized: true, marketCapB: 750 },
  { ticker: "V", name: "Visa Inc.", sector: "Financials", tokenized: true, marketCapB: 550 },
  { ticker: "MA", name: "Mastercard Inc.", sector: "Financials", tokenized: true, marketCapB: 480 },
  { ticker: "XOM", name: "Exxon Mobil Corp.", sector: "Energy", tokenized: true, marketCapB: 470 },
  { ticker: "UNH", name: "UnitedHealth Group", sector: "Health Care", tokenized: true, marketCapB: 450 },
  { ticker: "ORCL", name: "Oracle Corp.", sector: "Technology", tokenized: true, marketCapB: 450 },
  { ticker: "COST", name: "Costco Wholesale", sector: "Consumer Staples", tokenized: true, marketCapB: 420 },
  { ticker: "HD", name: "Home Depot", sector: "Consumer Disc.", tokenized: true, marketCapB: 400 },
  { ticker: "PG", name: "Procter & Gamble", sector: "Consumer Staples", tokenized: true, marketCapB: 380 },
  { ticker: "JNJ", name: "Johnson & Johnson", sector: "Health Care", tokenized: true, marketCapB: 380 },
  { ticker: "NFLX", name: "Netflix Inc.", sector: "Communication", tokenized: true, marketCapB: 380 },
  { ticker: "ABBV", name: "AbbVie Inc.", sector: "Health Care", tokenized: true, marketCapB: 350 },
  { ticker: "BAC", name: "Bank of America", sector: "Financials", tokenized: true, marketCapB: 320 },
  { ticker: "KO", name: "Coca-Cola Co.", sector: "Consumer Staples", tokenized: true, marketCapB: 280 },
  { ticker: "CVX", name: "Chevron Corp.", sector: "Energy", tokenized: true, marketCapB: 280 },
  { ticker: "CRM", name: "Salesforce Inc.", sector: "Technology", tokenized: true, marketCapB: 280 },
  { ticker: "AMD", name: "Advanced Micro Devices", sector: "Technology", tokenized: true, marketCapB: 260 },
  { ticker: "PEP", name: "PepsiCo Inc.", sector: "Consumer Staples", tokenized: true, marketCapB: 210 },
  { ticker: "TMO", name: "Thermo Fisher Scientific", sector: "Health Care", tokenized: false, marketCapB: 210 },
  { ticker: "LIN", name: "Linde plc", sector: "Materials", tokenized: true, marketCapB: 220 },
  { ticker: "MCD", name: "McDonald's Corp.", sector: "Consumer Disc.", tokenized: true, marketCapB: 210 },
  { ticker: "CSCO", name: "Cisco Systems", sector: "Technology", tokenized: true, marketCapB: 240 },
  { ticker: "WFC", name: "Wells Fargo & Co.", sector: "Financials", tokenized: false, marketCapB: 230 },
  { ticker: "ACN", name: "Accenture plc", sector: "Technology", tokenized: false, marketCapB: 210 },
  { ticker: "ABT", name: "Abbott Laboratories", sector: "Health Care", tokenized: false, marketCapB: 210 },
  { ticker: "IBM", name: "IBM Corp.", sector: "Technology", tokenized: true, marketCapB: 200 },
  { ticker: "DIS", name: "Walt Disney Co.", sector: "Communication", tokenized: true, marketCapB: 200 },
  { ticker: "GE", name: "General Electric", sector: "Industrials", tokenized: false, marketCapB: 200 },
  { ticker: "AXP", name: "American Express", sector: "Financials", tokenized: true, marketCapB: 200 },
  { ticker: "PM", name: "Philip Morris International", sector: "Consumer Staples", tokenized: true, marketCapB: 190 },
  { ticker: "QCOM", name: "Qualcomm Inc.", sector: "Technology", tokenized: true, marketCapB: 190 },
  { ticker: "CAT", name: "Caterpillar Inc.", sector: "Industrials", tokenized: true, marketCapB: 180 },
  { ticker: "VZ", name: "Verizon Communications", sector: "Communication", tokenized: true, marketCapB: 180 },
  { ticker: "TXN", name: "Texas Instruments", sector: "Technology", tokenized: true, marketCapB: 170 },
  { ticker: "INTU", name: "Intuit Inc.", sector: "Technology", tokenized: true, marketCapB: 180 },
  { ticker: "NOW", name: "ServiceNow Inc.", sector: "Technology", tokenized: true, marketCapB: 190 },
  { ticker: "ISRG", name: "Intuitive Surgical", sector: "Health Care", tokenized: true, marketCapB: 190 },
  { ticker: "AMGN", name: "Amgen Inc.", sector: "Health Care", tokenized: true, marketCapB: 160 },
  { ticker: "SPGI", name: "S&P Global", sector: "Financials", tokenized: false, marketCapB: 150 },
  { ticker: "BKNG", name: "Booking Holdings", sector: "Consumer Disc.", tokenized: true, marketCapB: 150 },
  { ticker: "PFE", name: "Pfizer Inc.", sector: "Health Care", tokenized: false, marketCapB: 150 },
  { ticker: "HON", name: "Honeywell International", sector: "Industrials", tokenized: true, marketCapB: 140 },
  { ticker: "UBER", name: "Uber Technologies", sector: "Industrials", tokenized: false, marketCapB: 150 },
  { ticker: "BA", name: "Boeing Co.", sector: "Industrials", tokenized: true, marketCapB: 130 },
  { ticker: "GS", name: "Goldman Sachs Group", sector: "Financials", tokenized: true, marketCapB: 200 },
  { ticker: "MS", name: "Morgan Stanley", sector: "Financials", tokenized: false, marketCapB: 180 },
  { ticker: "BLK", name: "BlackRock Inc.", sector: "Financials", tokenized: false, marketCapB: 150 },
  { ticker: "SCHW", name: "Charles Schwab", sector: "Financials", tokenized: false, marketCapB: 140 },
  { ticker: "T", name: "AT&T Inc.", sector: "Communication", tokenized: false, marketCapB: 160 },
  { ticker: "LOW", name: "Lowe's Companies", sector: "Consumer Disc.", tokenized: false, marketCapB: 140 },
  ]
};

MARKETS["FTSE"] = {
  name: "FTSE 100",
  city: "London",
  country: "UK",
  indexTicker: { ticker: "ISF", name: "iShares Core FTSE 100 ETF", sector: "Index", tokenized: false, marketCapB: 20 },
  constituents: [
  { ticker: "AZN", name: "AstraZeneca", sector: "Health Care", tokenized: false, marketCapB: 210 },
  { ticker: "SHEL", name: "Shell plc", sector: "Energy", tokenized: false, marketCapB: 220 },
  { ticker: "HSBA", name: "HSBC Holdings", sector: "Financials", tokenized: false, marketCapB: 180 },
  { ticker: "ULVR", name: "Unilever", sector: "Consumer Staples", tokenized: false, marketCapB: 130 },
  { ticker: "BP", name: "BP plc", sector: "Energy", tokenized: false, marketCapB: 90 },
  { ticker: "RIO", name: "Rio Tinto", sector: "Materials", tokenized: false, marketCapB: 95 },
  { ticker: "GSK", name: "GSK plc", sector: "Health Care", tokenized: false, marketCapB: 70 },
  { ticker: "DGE", name: "Diageo plc", sector: "Consumer Staples", tokenized: false, marketCapB: 55 },
  { ticker: "BATS", name: "British American Tobacco", sector: "Consumer Staples", tokenized: false, marketCapB: 70 },
  { ticker: "REL", name: "RELX plc", sector: "Industrials", tokenized: false, marketCapB: 90 },
  { ticker: "GLEN", name: "Glencore plc", sector: "Materials", tokenized: false, marketCapB: 55 },
  { ticker: "NG", name: "National Grid", sector: "Utilities", tokenized: false, marketCapB: 50 },
  { ticker: "LSEG", name: "London Stock Exchange Group", sector: "Financials", tokenized: false, marketCapB: 55 },
  { ticker: "AAL", name: "Anglo American", sector: "Materials", tokenized: false, marketCapB: 40 },
  { ticker: "BA.", name: "BAE Systems", sector: "Industrials", tokenized: false, marketCapB: 50 },
  { ticker: "VOD", name: "Vodafone Group", sector: "Communication", tokenized: false, marketCapB: 25 },
  { ticker: "LLOY", name: "Lloyds Banking Group", sector: "Financials", tokenized: false, marketCapB: 50 },
  { ticker: "BARC", name: "Barclays plc", sector: "Financials", tokenized: false, marketCapB: 45 },
  { ticker: "PRU", name: "Prudential plc", sector: "Financials", tokenized: false, marketCapB: 25 },
  { ticker: "CPG", name: "Compass Group", sector: "Consumer Disc.", tokenized: false, marketCapB: 50 },
  { ticker: "RKT", name: "Reckitt Benckiser", sector: "Consumer Staples", tokenized: false, marketCapB: 30 },
  { ticker: "IMB", name: "Imperial Brands", sector: "Consumer Staples", tokenized: false, marketCapB: 25 },
  { ticker: "NWG", name: "NatWest Group", sector: "Financials", tokenized: false, marketCapB: 40 },
  { ticker: "STAN", name: "Standard Chartered", sector: "Financials", tokenized: false, marketCapB: 30 },
  { ticker: "TSCO", name: "Tesco plc", sector: "Consumer Staples", tokenized: false, marketCapB: 30 },
  { ticker: "EXPN", name: "Experian plc", sector: "Industrials", tokenized: false, marketCapB: 40 },
  { ticker: "CRH", name: "CRH plc", sector: "Materials", tokenized: false, marketCapB: 55 },
  { ticker: "SSE", name: "SSE plc", sector: "Utilities", tokenized: false, marketCapB: 25 },
  { ticker: "SGE", name: "Sage Group", sector: "Technology", tokenized: false, marketCapB: 15 },
  { ticker: "AHT", name: "Ashtead Group", sector: "Industrials", tokenized: false, marketCapB: 25 },
  { ticker: "III", name: "3i Group", sector: "Financials", tokenized: false, marketCapB: 25 },
  { ticker: "FRES", name: "Fresnillo plc", sector: "Materials", tokenized: false, marketCapB: 15 },
  { ticker: "SMIN", name: "Smiths Group", sector: "Industrials", tokenized: false, marketCapB: 10 },
  { ticker: "WPP", name: "WPP plc", sector: "Communication", tokenized: false, marketCapB: 10 },
  { ticker: "ITRK", name: "Intertek Group", sector: "Industrials", tokenized: false, marketCapB: 10 },
  { ticker: "SN", name: "Smith & Nephew", sector: "Health Care", tokenized: false, marketCapB: 10 },
  { ticker: "HLN", name: "Haleon plc", sector: "Consumer Staples", tokenized: false, marketCapB: 35 },
  { ticker: "ANTO", name: "Antofagasta plc", sector: "Materials", tokenized: false, marketCapB: 20 },
  ]
};

MARKETS["GDAXI"] = {
  name: "DAX",
  city: "Frankfurt",
  country: "Germany",
  indexTicker: { ticker: "EXS1", name: "iShares Core DAX UCITS ETF", sector: "Index", tokenized: false, marketCapB: 45 },
  constituents: [
  { ticker: "SAP", name: "SAP SE", sector: "Technology", tokenized: false, marketCapB: 230 },
  { ticker: "SIE", name: "Siemens AG", sector: "Industrials", tokenized: false, marketCapB: 140 },
  { ticker: "ALV", name: "Allianz SE", sector: "Financials", tokenized: false, marketCapB: 130 },
  { ticker: "DTE", name: "Deutsche Telekom", sector: "Communication", tokenized: false, marketCapB: 120 },
  { ticker: "MRK.DE", name: "Merck KGaA", sector: "Health Care", tokenized: false, marketCapB: 70 },
  { ticker: "MBG", name: "Mercedes-Benz Group", sector: "Consumer Disc.", tokenized: false, marketCapB: 55 },
  { ticker: "BMW", name: "BMW AG", sector: "Consumer Disc.", tokenized: false, marketCapB: 55 },
  { ticker: "AIR", name: "Airbus SE", sector: "Industrials", tokenized: false, marketCapB: 140 },
  { ticker: "MUV2", name: "Munich Re", sector: "Financials", tokenized: false, marketCapB: 65 },
  { ticker: "DBK", name: "Deutsche Bank", sector: "Financials", tokenized: false, marketCapB: 35 },
  { ticker: "BAS", name: "BASF SE", sector: "Materials", tokenized: false, marketCapB: 45 },
  { ticker: "VOW3", name: "Volkswagen AG", sector: "Consumer Disc.", tokenized: false, marketCapB: 55 },
  { ticker: "IFX", name: "Infineon Technologies", sector: "Technology", tokenized: false, marketCapB: 40 },
  { ticker: "DPW", name: "DHL Group", sector: "Industrials", tokenized: false, marketCapB: 45 },
  { ticker: "DB1", name: "Deutsche Boerse", sector: "Financials", tokenized: false, marketCapB: 55 },
  { ticker: "RWE", name: "RWE AG", sector: "Utilities", tokenized: false, marketCapB: 25 },
  { ticker: "EOAN", name: "E.ON SE", sector: "Utilities", tokenized: false, marketCapB: 35 },
  { ticker: "HEN3", name: "Henkel AG", sector: "Consumer Staples", tokenized: false, marketCapB: 20 },
  { ticker: "ADS", name: "Adidas AG", sector: "Consumer Disc.", tokenized: false, marketCapB: 40 },
  { ticker: "BAYN", name: "Bayer AG", sector: "Health Care", tokenized: false, marketCapB: 25 },
  { ticker: "HEI", name: "HeidelbergMaterials", sector: "Materials", tokenized: false, marketCapB: 20 },
  { ticker: "FRE", name: "Fresenius SE", sector: "Health Care", tokenized: false, marketCapB: 20 },
  { ticker: "VNA", name: "Vonovia SE", sector: "Financials", tokenized: false, marketCapB: 25 },
  { ticker: "CON", name: "Continental AG", sector: "Consumer Disc.", tokenized: false, marketCapB: 8 },
  { ticker: "SY1", name: "Symrise AG", sector: "Materials", tokenized: false, marketCapB: 15 },
  { ticker: "ZAL", name: "Zalando SE", sector: "Consumer Disc.", tokenized: false, marketCapB: 8 },
  { ticker: "PAH3", name: "Porsche SE", sector: "Consumer Disc.", tokenized: false, marketCapB: 15 },
  { ticker: "P911", name: "Porsche AG", sector: "Consumer Disc.", tokenized: false, marketCapB: 30 },
  { ticker: "MTX", name: "MTU Aero Engines", sector: "Industrials", tokenized: false, marketCapB: 20 },
  { ticker: "SRT3", name: "Sartorius AG", sector: "Health Care", tokenized: false, marketCapB: 18 },
  { ticker: "QIA", name: "Qiagen NV", sector: "Health Care", tokenized: false, marketCapB: 10 },
  { ticker: "BEI", name: "Beiersdorf AG", sector: "Consumer Staples", tokenized: false, marketCapB: 30 },
  { ticker: "BNR", name: "Brenntag SE", sector: "Industrials", tokenized: false, marketCapB: 8 },
  { ticker: "ENR", name: "Siemens Energy", sector: "Industrials", tokenized: false, marketCapB: 50 },
  { ticker: "HNR1", name: "Hannover Rueck", sector: "Financials", tokenized: false, marketCapB: 35 },
  { ticker: "RHM", name: "Rheinmetall AG", sector: "Industrials", tokenized: false, marketCapB: 45 },
  { ticker: "1COV", name: "Covestro AG", sector: "Materials", tokenized: false, marketCapB: 10 },
  { ticker: "SHL", name: "Siemens Healthineers", sector: "Health Care", tokenized: false, marketCapB: 50 },
  ]
};

MARKETS["FCHI"] = {
  name: "CAC 40",
  city: "Paris",
  country: "France",
  indexTicker: { ticker: "CACX", name: "Amundi CAC 40 UCITS ETF", sector: "Index", tokenized: false, marketCapB: 25 },
  constituents: [
  { ticker: "MC", name: "LVMH", sector: "Consumer Disc.", tokenized: false, marketCapB: 320 },
  { ticker: "OR", name: "L'Oreal", sector: "Consumer Staples", tokenized: false, marketCapB: 180 },
  { ticker: "TTE", name: "TotalEnergies", sector: "Energy", tokenized: false, marketCapB: 150 },
  { ticker: "SU", name: "Schneider Electric", sector: "Industrials", tokenized: false, marketCapB: 130 },
  { ticker: "SAN", name: "Sanofi", sector: "Health Care", tokenized: false, marketCapB: 130 },
  { ticker: "AI", name: "Air Liquide", sector: "Materials", tokenized: false, marketCapB: 100 },
  { ticker: "EL", name: "EssilorLuxottica", sector: "Health Care", tokenized: false, marketCapB: 120 },
  { ticker: "RMS", name: "Hermes International", sector: "Consumer Disc.", tokenized: false, marketCapB: 250 },
  { ticker: "BNP", name: "BNP Paribas", sector: "Financials", tokenized: false, marketCapB: 90 },
  { ticker: "CS", name: "AXA SA", sector: "Financials", tokenized: false, marketCapB: 90 },
  { ticker: "DG", name: "Vinci SA", sector: "Industrials", tokenized: false, marketCapB: 70 },
  { ticker: "SGO", name: "Cie de Saint-Gobain", sector: "Industrials", tokenized: false, marketCapB: 45 },
  { ticker: "ML", name: "Michelin", sector: "Consumer Disc.", tokenized: false, marketCapB: 15 },
  { ticker: "KER", name: "Kering SA", sector: "Consumer Disc.", tokenized: false, marketCapB: 30 },
  { ticker: "BN", name: "Danone SA", sector: "Consumer Staples", tokenized: false, marketCapB: 45 },
  { ticker: "ACA", name: "Credit Agricole", sector: "Financials", tokenized: false, marketCapB: 45 },
  { ticker: "GLE", name: "Societe Generale", sector: "Financials", tokenized: false, marketCapB: 30 },
  { ticker: "VIE", name: "Veolia Environnement", sector: "Utilities", tokenized: false, marketCapB: 22 },
  { ticker: "ENGI", name: "Engie SA", sector: "Utilities", tokenized: false, marketCapB: 40 },
  { ticker: "CAP", name: "Capgemini SE", sector: "Technology", tokenized: false, marketCapB: 25 },
  { ticker: "STLAM", name: "Stellantis NV", sector: "Consumer Disc.", tokenized: false, marketCapB: 30 },
  { ticker: "PUB", name: "Publicis Groupe", sector: "Communication", tokenized: false, marketCapB: 25 },
  { ticker: "SAF", name: "Safran SA", sector: "Industrials", tokenized: false, marketCapB: 100 },
  { ticker: "HO", name: "Thales SA", sector: "Industrials", tokenized: false, marketCapB: 50 },
  { ticker: "LR", name: "Legrand SA", sector: "Industrials", tokenized: false, marketCapB: 25 },
  { ticker: "RI", name: "Pernod Ricard", sector: "Consumer Staples", tokenized: false, marketCapB: 30 },
  { ticker: "VIV", name: "Vivendi SE", sector: "Communication", tokenized: false, marketCapB: 8 },
  { ticker: "ORA", name: "Orange SA", sector: "Communication", tokenized: false, marketCapB: 30 },
  { ticker: "EN", name: "Bollore SE", sector: "Industrials", tokenized: false, marketCapB: 20 },
  { ticker: "STMPA", name: "STMicroelectronics", sector: "Technology", tokenized: false, marketCapB: 25 },
  { ticker: "WLN", name: "Worldline SA", sector: "Technology", tokenized: false, marketCapB: 3 },
  { ticker: "URW", name: "Unibail-Rodamco-Westfield", sector: "Financials", tokenized: false, marketCapB: 12 },
  { ticker: "TEP", name: "Teleperformance SE", sector: "Industrials", tokenized: false, marketCapB: 6 },
  { ticker: "EDEN", name: "Edenred SA", sector: "Industrials", tokenized: false, marketCapB: 10 },
  { ticker: "ALO", name: "Alstom SA", sector: "Industrials", tokenized: false, marketCapB: 8 },
  { ticker: "ERF", name: "Eurofins Scientific", sector: "Health Care", tokenized: false, marketCapB: 15 },
  { ticker: "FR", name: "Valeo SE", sector: "Consumer Disc.", tokenized: false, marketCapB: 4 },
  { ticker: "ARGX", name: "Argenx SE", sector: "Health Care", tokenized: false, marketCapB: 35 },
  ]
};

MARKETS["STOXX50E"] = {
  name: "Euro Stoxx 50",
  city: "Frankfurt",
  country: "Eurozone",
  indexTicker: { ticker: "SX5E", name: "iShares EURO STOXX 50 UCITS ETF", sector: "Index", tokenized: false, marketCapB: 40 },
  constituents: [
  { ticker: "ASML", name: "ASML Holding", sector: "Technology", tokenized: false, marketCapB: 320 },
  { ticker: "MC", name: "LVMH", sector: "Consumer Disc.", tokenized: false, marketCapB: 320 },
  { ticker: "SAP", name: "SAP SE", sector: "Technology", tokenized: false, marketCapB: 230 },
  { ticker: "TTE", name: "TotalEnergies", sector: "Energy", tokenized: false, marketCapB: 150 },
  { ticker: "SAN", name: "Sanofi", sector: "Health Care", tokenized: false, marketCapB: 130 },
  { ticker: "SIE", name: "Siemens AG", sector: "Industrials", tokenized: false, marketCapB: 140 },
  { ticker: "ALV", name: "Allianz SE", sector: "Financials", tokenized: false, marketCapB: 130 },
  { ticker: "AIR", name: "Airbus SE", sector: "Industrials", tokenized: false, marketCapB: 140 },
  { ticker: "OR", name: "L'Oreal", sector: "Consumer Staples", tokenized: false, marketCapB: 180 },
  { ticker: "SU", name: "Schneider Electric", sector: "Industrials", tokenized: false, marketCapB: 130 },
  { ticker: "ITX", name: "Inditex SA", sector: "Consumer Disc.", tokenized: false, marketCapB: 150 },
  { ticker: "DTE", name: "Deutsche Telekom", sector: "Communication", tokenized: false, marketCapB: 120 },
  { ticker: "IBE", name: "Iberdrola SA", sector: "Utilities", tokenized: false, marketCapB: 90 },
  { ticker: "ENEL", name: "Enel SpA", sector: "Utilities", tokenized: false, marketCapB: 80 },
  { ticker: "BNP", name: "BNP Paribas", sector: "Financials", tokenized: false, marketCapB: 90 },
  { ticker: "MUV2", name: "Munich Re", sector: "Financials", tokenized: false, marketCapB: 65 },
  { ticker: "AI", name: "Air Liquide", sector: "Materials", tokenized: false, marketCapB: 100 },
  { ticker: "ADYEN", name: "Adyen NV", sector: "Technology", tokenized: false, marketCapB: 45 },
  { ticker: "CS", name: "AXA SA", sector: "Financials", tokenized: false, marketCapB: 90 },
  { ticker: "BAS", name: "BASF SE", sector: "Materials", tokenized: false, marketCapB: 45 },
  { ticker: "DG", name: "Vinci SA", sector: "Industrials", tokenized: false, marketCapB: 70 },
  { ticker: "RMS", name: "Hermes International", sector: "Consumer Disc.", tokenized: false, marketCapB: 250 },
  { ticker: "EL", name: "EssilorLuxottica", sector: "Health Care", tokenized: false, marketCapB: 120 },
  { ticker: "ISP", name: "Intesa Sanpaolo", sector: "Financials", tokenized: false, marketCapB: 90 },
  { ticker: "UCG", name: "UniCredit SpA", sector: "Financials", tokenized: false, marketCapB: 90 },
  { ticker: "PRX", name: "Prosus NV", sector: "Technology", tokenized: false, marketCapB: 100 },
  { ticker: "BBVA", name: "BBVA", sector: "Financials", tokenized: false, marketCapB: 70 },
  { ticker: "VOW3", name: "Volkswagen AG", sector: "Consumer Disc.", tokenized: false, marketCapB: 55 },
  { ticker: "MBG", name: "Mercedes-Benz Group", sector: "Consumer Disc.", tokenized: false, marketCapB: 55 },
  { ticker: "BMW", name: "BMW AG", sector: "Consumer Disc.", tokenized: false, marketCapB: 55 },
  { ticker: "PHIA", name: "Koninklijke Philips", sector: "Health Care", tokenized: false, marketCapB: 25 },
  { ticker: "INGA", name: "ING Groep", sector: "Financials", tokenized: false, marketCapB: 55 },
  { ticker: "ABI", name: "Anheuser-Busch InBev", sector: "Consumer Staples", tokenized: false, marketCapB: 115 },
  { ticker: "KER", name: "Kering SA", sector: "Consumer Disc.", tokenized: false, marketCapB: 30 },
  { ticker: "STLAM", name: "Stellantis NV", sector: "Consumer Disc.", tokenized: false, marketCapB: 30 },
  { ticker: "SAF", name: "Safran SA", sector: "Industrials", tokenized: false, marketCapB: 100 },
  { ticker: "DB1", name: "Deutsche Boerse", sector: "Financials", tokenized: false, marketCapB: 55 },
  { ticker: "NOKIA", name: "Nokia Oyj", sector: "Technology", tokenized: false, marketCapB: 25 },
  { ticker: "RACE", name: "Ferrari NV", sector: "Consumer Disc.", tokenized: false, marketCapB: 90 },
  { ticker: "FLTR", name: "Flutter Entertainment", sector: "Consumer Disc.", tokenized: false, marketCapB: 40 },
  { ticker: "CRH", name: "CRH plc", sector: "Materials", tokenized: false, marketCapB: 55 },
  { ticker: "ENI", name: "Eni SpA", sector: "Energy", tokenized: false, marketCapB: 50 },
  { ticker: "RI", name: "Pernod Ricard", sector: "Consumer Staples", tokenized: false, marketCapB: 30 },
  { ticker: "G", name: "Assicurazioni Generali", sector: "Financials", tokenized: false, marketCapB: 45 },
  { ticker: "VNA", name: "Vonovia SE", sector: "Financials", tokenized: false, marketCapB: 25 },
  { ticker: "BAYN", name: "Bayer AG", sector: "Health Care", tokenized: false, marketCapB: 25 },
  { ticker: "HO", name: "Thales SA", sector: "Industrials", tokenized: false, marketCapB: 50 },
  { ticker: "WKL", name: "Wolters Kluwer", sector: "Industrials", tokenized: false, marketCapB: 35 },
  ]
};

MARKETS["N225"] = {
  name: "Nikkei 225",
  city: "Tokyo",
  country: "Japan",
  indexTicker: { ticker: "1321.T", name: "Nomura Nikkei 225 ETF", sector: "Index", tokenized: false, marketCapB: 20 },
  constituents: [
  { ticker: "7203", name: "Toyota Motor", sector: "Consumer Disc.", tokenized: false, marketCapB: 250 },
  { ticker: "6758", name: "Sony Group", sector: "Technology", tokenized: false, marketCapB: 130 },
  { ticker: "9984", name: "SoftBank Group", sector: "Communication", tokenized: false, marketCapB: 90 },
  { ticker: "8306", name: "Mitsubishi UFJ Financial", sector: "Financials", tokenized: false, marketCapB: 130 },
  { ticker: "6501", name: "Hitachi Ltd.", sector: "Industrials", tokenized: false, marketCapB: 110 },
  { ticker: "6098", name: "Recruit Holdings", sector: "Industrials", tokenized: false, marketCapB: 80 },
  { ticker: "9432", name: "Nippon Telegraph & Telephone", sector: "Communication", tokenized: false, marketCapB: 90 },
  { ticker: "8035", name: "Tokyo Electron", sector: "Technology", tokenized: false, marketCapB: 100 },
  { ticker: "6857", name: "Advantest Corp.", sector: "Technology", tokenized: false, marketCapB: 80 },
  { ticker: "4063", name: "Shin-Etsu Chemical", sector: "Materials", tokenized: false, marketCapB: 90 },
  { ticker: "7267", name: "Honda Motor", sector: "Consumer Disc.", tokenized: false, marketCapB: 60 },
  { ticker: "6902", name: "Denso Corp.", sector: "Consumer Disc.", tokenized: false, marketCapB: 50 },
  { ticker: "8058", name: "Mitsubishi Corp.", sector: "Industrials", tokenized: false, marketCapB: 70 },
  { ticker: "8031", name: "Mitsui & Co.", sector: "Industrials", tokenized: false, marketCapB: 55 },
  { ticker: "9433", name: "KDDI Corp.", sector: "Communication", tokenized: false, marketCapB: 70 },
  { ticker: "4568", name: "Daiichi Sankyo", sector: "Health Care", tokenized: false, marketCapB: 90 },
  { ticker: "6981", name: "Murata Manufacturing", sector: "Technology", tokenized: false, marketCapB: 45 },
  { ticker: "7974", name: "Nintendo Co.", sector: "Communication", tokenized: false, marketCapB: 80 },
  { ticker: "6367", name: "Daikin Industries", sector: "Industrials", tokenized: false, marketCapB: 45 },
  { ticker: "9983", name: "Fast Retailing", sector: "Consumer Disc.", tokenized: false, marketCapB: 90 },
  { ticker: "4519", name: "Chugai Pharmaceutical", sector: "Health Care", tokenized: false, marketCapB: 55 },
  { ticker: "8801", name: "Mitsui Fudosan", sector: "Financials", tokenized: false, marketCapB: 30 },
  { ticker: "8766", name: "Tokio Marine Holdings", sector: "Financials", tokenized: false, marketCapB: 70 },
  { ticker: "8316", name: "Sumitomo Mitsui Financial", sector: "Financials", tokenized: false, marketCapB: 100 },
  { ticker: "2914", name: "Japan Tobacco", sector: "Consumer Staples", tokenized: false, marketCapB: 55 },
  { ticker: "4661", name: "Oriental Land Co.", sector: "Consumer Disc.", tokenized: false, marketCapB: 40 },
  { ticker: "6503", name: "Mitsubishi Electric", sector: "Industrials", tokenized: false, marketCapB: 40 },
  { ticker: "7011", name: "Mitsubishi Heavy Industries", sector: "Industrials", tokenized: false, marketCapB: 70 },
  { ticker: "6273", name: "SMC Corp.", sector: "Industrials", tokenized: false, marketCapB: 40 },
  { ticker: "9020", name: "East Japan Railway", sector: "Industrials", tokenized: false, marketCapB: 30 },
  { ticker: "4543", name: "Terumo Corp.", sector: "Health Care", tokenized: false, marketCapB: 30 },
  { ticker: "6178", name: "Japan Post Holdings", sector: "Financials", tokenized: false, marketCapB: 25 },
  { ticker: "8411", name: "Mizuho Financial Group", sector: "Financials", tokenized: false, marketCapB: 70 },
  { ticker: "5108", name: "Bridgestone Corp.", sector: "Consumer Disc.", tokenized: false, marketCapB: 30 },
  { ticker: "6702", name: "Fujitsu Ltd.", sector: "Technology", tokenized: false, marketCapB: 35 },
  { ticker: "4901", name: "Fujifilm Holdings", sector: "Technology", tokenized: false, marketCapB: 30 },
  { ticker: "6971", name: "Kyocera Corp.", sector: "Technology", tokenized: false, marketCapB: 22 },
  { ticker: "6301", name: "Komatsu Ltd.", sector: "Industrials", tokenized: false, marketCapB: 30 },
  { ticker: "8802", name: "Mitsubishi Estate", sector: "Financials", tokenized: false, marketCapB: 25 },
  { ticker: "6752", name: "Panasonic Holdings", sector: "Technology", tokenized: false, marketCapB: 25 },
  { ticker: "9022", name: "Central Japan Railway", sector: "Industrials", tokenized: false, marketCapB: 35 },
  { ticker: "5401", name: "Nippon Steel Corp.", sector: "Materials", tokenized: false, marketCapB: 25 },
  { ticker: "3382", name: "Seven & i Holdings", sector: "Consumer Staples", tokenized: false, marketCapB: 30 },
  { ticker: "8267", name: "Aeon Co.", sector: "Consumer Staples", tokenized: false, marketCapB: 25 },
  { ticker: "4452", name: "Kao Corp.", sector: "Consumer Staples", tokenized: false, marketCapB: 25 },
  { ticker: "1925", name: "Daiwa House Industry", sector: "Financials", tokenized: false, marketCapB: 20 },
  { ticker: "7741", name: "Hoya Corp.", sector: "Health Care", tokenized: false, marketCapB: 35 },
  { ticker: "2802", name: "Ajinomoto Co.", sector: "Consumer Staples", tokenized: false, marketCapB: 20 },
  ]
};

MARKETS["HSI"] = {
  name: "Hang Seng Index",
  city: "Hong Kong",
  country: "China",
  indexTicker: { ticker: "2833.HK", name: "Tracker Fund of Hong Kong", sector: "Index", tokenized: false, marketCapB: 15 },
  constituents: [
  { ticker: "0700", name: "Tencent Holdings", sector: "Communication", tokenized: false, marketCapB: 450 },
  { ticker: "9988", name: "Alibaba Group", sector: "Consumer Disc.", tokenized: false, marketCapB: 250 },
  { ticker: "3690", name: "Meituan", sector: "Consumer Disc.", tokenized: false, marketCapB: 80 },
  { ticker: "1299", name: "AIA Group", sector: "Financials", tokenized: false, marketCapB: 90 },
  { ticker: "0939", name: "China Construction Bank", sector: "Financials", tokenized: false, marketCapB: 180 },
  { ticker: "0005", name: "HSBC Holdings", sector: "Financials", tokenized: false, marketCapB: 180 },
  { ticker: "1398", name: "Industrial & Commercial Bank of China", sector: "Financials", tokenized: false, marketCapB: 220 },
  { ticker: "0388", name: "Hong Kong Exchanges & Clearing", sector: "Financials", tokenized: false, marketCapB: 50 },
  { ticker: "2318", name: "Ping An Insurance", sector: "Financials", tokenized: false, marketCapB: 100 },
  { ticker: "9999", name: "NetEase Inc.", sector: "Communication", tokenized: false, marketCapB: 65 },
  { ticker: "1211", name: "BYD Company", sector: "Consumer Disc.", tokenized: false, marketCapB: 100 },
  { ticker: "0857", name: "PetroChina", sector: "Energy", tokenized: false, marketCapB: 180 },
  { ticker: "3968", name: "China Merchants Bank", sector: "Financials", tokenized: false, marketCapB: 130 },
  { ticker: "0688", name: "China Overseas Land & Investment", sector: "Financials", tokenized: false, marketCapB: 15 },
  { ticker: "2020", name: "ANTA Sports Products", sector: "Consumer Disc.", tokenized: false, marketCapB: 20 },
  { ticker: "1810", name: "Xiaomi Corp.", sector: "Technology", tokenized: false, marketCapB: 130 },
  { ticker: "0016", name: "Sun Hung Kai Properties", sector: "Financials", tokenized: false, marketCapB: 25 },
  { ticker: "0027", name: "Galaxy Entertainment Group", sector: "Consumer Disc.", tokenized: false, marketCapB: 15 },
  { ticker: "0883", name: "CNOOC Ltd.", sector: "Energy", tokenized: false, marketCapB: 90 },
  { ticker: "1109", name: "China Resources Land", sector: "Financials", tokenized: false, marketCapB: 20 },
  { ticker: "0002", name: "CLP Holdings", sector: "Utilities", tokenized: false, marketCapB: 20 },
  { ticker: "0003", name: "Hong Kong & China Gas", sector: "Utilities", tokenized: false, marketCapB: 12 },
  { ticker: "0006", name: "Power Assets Holdings", sector: "Utilities", tokenized: false, marketCapB: 10 },
  { ticker: "1928", name: "Sands China Ltd.", sector: "Consumer Disc.", tokenized: false, marketCapB: 20 },
  { ticker: "0011", name: "Hang Seng Bank", sector: "Financials", tokenized: false, marketCapB: 30 },
  { ticker: "0012", name: "Henderson Land Development", sector: "Financials", tokenized: false, marketCapB: 12 },
  { ticker: "0175", name: "Geely Automobile", sector: "Consumer Disc.", tokenized: false, marketCapB: 20 },
  { ticker: "0288", name: "WH Group", sector: "Consumer Staples", tokenized: false, marketCapB: 10 },
  { ticker: "0322", name: "Tingyi (Master Kong)", sector: "Consumer Staples", tokenized: false, marketCapB: 10 },
  { ticker: "0669", name: "Techtronic Industries", sector: "Industrials", tokenized: false, marketCapB: 25 },
  { ticker: "0762", name: "China Unicom", sector: "Communication", tokenized: false, marketCapB: 20 },
  { ticker: "0823", name: "Link REIT", sector: "Financials", tokenized: false, marketCapB: 12 },
  { ticker: "0868", name: "Xinyi Glass Holdings", sector: "Materials", tokenized: false, marketCapB: 6 },
  { ticker: "0941", name: "China Mobile", sector: "Communication", tokenized: false, marketCapB: 210 },
  { ticker: "0960", name: "Longfor Group", sector: "Financials", tokenized: false, marketCapB: 8 },
  { ticker: "0968", name: "Xinyi Solar Holdings", sector: "Industrials", tokenized: false, marketCapB: 5 },
  { ticker: "1044", name: "Hengan International", sector: "Consumer Staples", tokenized: false, marketCapB: 5 },
  { ticker: "1088", name: "China Shenhua Energy", sector: "Energy", tokenized: false, marketCapB: 40 },
  { ticker: "1093", name: "CSPC Pharmaceutical Group", sector: "Health Care", tokenized: false, marketCapB: 8 },
  { ticker: "1177", name: "Sino Biopharmaceutical", sector: "Health Care", tokenized: false, marketCapB: 6 },
  { ticker: "1972", name: "Swire Properties", sector: "Financials", tokenized: false, marketCapB: 8 },
  { ticker: "2318HK", name: "placeholder", sector: "Financials", tokenized: false, marketCapB: 1 },
  { ticker: "2313", name: "Shenzhou International", sector: "Consumer Disc.", tokenized: false, marketCapB: 10 },
  { ticker: "2331", name: "Li Ning Co.", sector: "Consumer Disc.", tokenized: false, marketCapB: 6 },
  { ticker: "2359", name: "China Pharma. (WuXi)", sector: "Health Care", tokenized: false, marketCapB: 25 },
  { ticker: "2382", name: "Sunny Optical Technology", sector: "Technology", tokenized: false, marketCapB: 8 },
  { ticker: "2388", name: "BOC Hong Kong Holdings", sector: "Financials", tokenized: false, marketCapB: 22 },
  { ticker: "2628", name: "China Life Insurance", sector: "Financials", tokenized: false, marketCapB: 50 },
  { ticker: "3328", name: "Bank of Communications", sector: "Financials", tokenized: false, marketCapB: 60 },
  { ticker: "3888", name: "Kingsoft Corp.", sector: "Technology", tokenized: false, marketCapB: 10 },
  { ticker: "6098HSI", name: "placeholder2", sector: "Industrials", tokenized: false, marketCapB: 1 },
  { ticker: "6862", name: "Haidilao International", sector: "Consumer Disc.", tokenized: false, marketCapB: 10 },
  ]
};

MARKETS["SSEC"] = {
  name: "Shanghai Composite",
  city: "Shanghai",
  country: "China",
  indexTicker: { ticker: "510760.SS", name: "China A-Shares major-constituent proxy", sector: "Index", tokenized: false, marketCapB: 10 },
  constituents: [
  { ticker: "600519", name: "Kweichow Moutai", sector: "Consumer Staples", tokenized: false, marketCapB: 280 },
  { ticker: "601398", name: "Industrial & Commercial Bank of China (A)", sector: "Financials", tokenized: false, marketCapB: 220 },
  { ticker: "601288", name: "Agricultural Bank of China (A)", sector: "Financials", tokenized: false, marketCapB: 150 },
  { ticker: "601988", name: "Bank of China (A)", sector: "Financials", tokenized: false, marketCapB: 130 },
  { ticker: "600036", name: "China Merchants Bank (A)", sector: "Financials", tokenized: false, marketCapB: 130 },
  { ticker: "601318", name: "Ping An Insurance (A)", sector: "Financials", tokenized: false, marketCapB: 100 },
  { ticker: "601857", name: "PetroChina (A)", sector: "Energy", tokenized: false, marketCapB: 180 },
  { ticker: "600028", name: "Sinopec (A)", sector: "Energy", tokenized: false, marketCapB: 90 },
  { ticker: "601628", name: "China Life Insurance (A)", sector: "Financials", tokenized: false, marketCapB: 50 },
  { ticker: "600276", name: "Jiangsu Hengrui Medicine", sector: "Health Care", tokenized: false, marketCapB: 30 },
  { ticker: "601166", name: "Industrial Bank Co.", sector: "Financials", tokenized: false, marketCapB: 50 },
  { ticker: "600887", name: "Inner Mongolia Yili Industrial", sector: "Consumer Staples", tokenized: false, marketCapB: 20 },
  { ticker: "601899", name: "Zijin Mining Group (A)", sector: "Materials", tokenized: false, marketCapB: 50 },
  { ticker: "600030", name: "CITIC Securities (A)", sector: "Financials", tokenized: false, marketCapB: 40 },
  { ticker: "601601", name: "China Pacific Insurance (A)", sector: "Financials", tokenized: false, marketCapB: 35 },
  { ticker: "600009", name: "Shanghai International Airport", sector: "Industrials", tokenized: false, marketCapB: 12 },
  { ticker: "601088", name: "China Shenhua Energy (A)", sector: "Energy", tokenized: false, marketCapB: 40 },
  { ticker: "600690", name: "Haier Smart Home", sector: "Consumer Disc.", tokenized: false, marketCapB: 25 },
  { ticker: "601818", name: "China Everbright Bank", sector: "Financials", tokenized: false, marketCapB: 25 },
  { ticker: "600585", name: "Anhui Conch Cement", sector: "Materials", tokenized: false, marketCapB: 20 },
  { ticker: "601668", name: "China State Construction Engineering", sector: "Industrials", tokenized: false, marketCapB: 30 },
  { ticker: "600050", name: "China United Network Communications", sector: "Communication", tokenized: false, marketCapB: 15 },
  { ticker: "601006", name: "Daqin Railway", sector: "Industrials", tokenized: false, marketCapB: 10 },
  { ticker: "600809", name: "Shanxi Xinghuacun Fen Wine", sector: "Consumer Staples", tokenized: false, marketCapB: 15 },
  { ticker: "600000", name: "Shanghai Pudong Development Bank", sector: "Financials", tokenized: false, marketCapB: 25 },
  { ticker: "601336", name: "New China Life Insurance", sector: "Financials", tokenized: false, marketCapB: 15 },
  { ticker: "600048", name: "Poly Developments and Holdings", sector: "Financials", tokenized: false, marketCapB: 12 },
  { ticker: "601211", name: "Guotai Junan Securities", sector: "Financials", tokenized: false, marketCapB: 15 },
  { ticker: "600025", name: "Huaneng Lancang River Hydropower", sector: "Utilities", tokenized: false, marketCapB: 8 },
  { ticker: "601728", name: "China Telecom (A)", sector: "Communication", tokenized: false, marketCapB: 50 },
  { ticker: "600016", name: "China Minsheng Banking", sector: "Financials", tokenized: false, marketCapB: 15 },
  { ticker: "601186", name: "China Railway Construction", sector: "Industrials", tokenized: false, marketCapB: 15 },
  { ticker: "600837", name: "Haitong Securities", sector: "Financials", tokenized: false, marketCapB: 12 },
  { ticker: "601878", name: "Zheshang Securities", sector: "Financials", tokenized: false, marketCapB: 5 },
  { ticker: "600893", name: "AECC Aviation Power", sector: "Industrials", tokenized: false, marketCapB: 15 },
  { ticker: "601998", name: "China CITIC Bank", sector: "Financials", tokenized: false, marketCapB: 30 },
  ]
};

MARKETS["KS11"] = {
  name: "KOSPI",
  city: "Seoul",
  country: "South Korea",
  indexTicker: { ticker: "069500.KS", name: "KODEX 200 ETF", sector: "Index", tokenized: false, marketCapB: 15 },
  constituents: [
  { ticker: "005930", name: "Samsung Electronics", sector: "Technology", tokenized: false, marketCapB: 380 },
  { ticker: "000660", name: "SK Hynix", sector: "Technology", tokenized: false, marketCapB: 120 },
  { ticker: "373220", name: "LG Energy Solution", sector: "Industrials", tokenized: false, marketCapB: 70 },
  { ticker: "207940", name: "Samsung Biologics", sector: "Health Care", tokenized: false, marketCapB: 60 },
  { ticker: "005380", name: "Hyundai Motor", sector: "Consumer Disc.", tokenized: false, marketCapB: 45 },
  { ticker: "051910", name: "LG Chem", sector: "Materials", tokenized: false, marketCapB: 25 },
  { ticker: "006400", name: "Samsung SDI", sector: "Technology", tokenized: false, marketCapB: 20 },
  { ticker: "000270", name: "Kia Corp.", sector: "Consumer Disc.", tokenized: false, marketCapB: 35 },
  { ticker: "035420", name: "NAVER Corp.", sector: "Communication", tokenized: false, marketCapB: 25 },
  { ticker: "105560", name: "KB Financial Group", sector: "Financials", tokenized: false, marketCapB: 30 },
  { ticker: "055550", name: "Shinhan Financial Group", sector: "Financials", tokenized: false, marketCapB: 28 },
  { ticker: "012330", name: "Hyundai Mobis", sector: "Consumer Disc.", tokenized: false, marketCapB: 20 },
  { ticker: "068270", name: "Celltrion", sector: "Health Care", tokenized: false, marketCapB: 20 },
  { ticker: "028260", name: "Samsung C&T Corp.", sector: "Industrials", tokenized: false, marketCapB: 18 },
  { ticker: "066570", name: "LG Electronics", sector: "Technology", tokenized: false, marketCapB: 15 },
  { ticker: "003670", name: "POSCO Holdings", sector: "Materials", tokenized: false, marketCapB: 20 },
  { ticker: "035720", name: "Kakao Corp.", sector: "Communication", tokenized: false, marketCapB: 12 },
  { ticker: "017670", name: "SK Telecom", sector: "Communication", tokenized: false, marketCapB: 12 },
  { ticker: "032830", name: "Samsung Life Insurance", sector: "Financials", tokenized: false, marketCapB: 15 },
  { ticker: "018260", name: "Samsung SDS", sector: "Technology", tokenized: false, marketCapB: 10 },
  { ticker: "015760", name: "Korea Electric Power", sector: "Utilities", tokenized: false, marketCapB: 15 },
  { ticker: "086790", name: "Hana Financial Group", sector: "Financials", tokenized: false, marketCapB: 18 },
  { ticker: "259960", name: "Krafton Inc.", sector: "Communication", tokenized: false, marketCapB: 10 },
  { ticker: "047810", name: "Korea Aerospace Industries", sector: "Industrials", tokenized: false, marketCapB: 10 },
  { ticker: "034730", name: "SK Inc.", sector: "Industrials", tokenized: false, marketCapB: 8 },
  { ticker: "010130", name: "Korea Zinc", sector: "Materials", tokenized: false, marketCapB: 8 },
  { ticker: "011200", name: "HMM Co.", sector: "Industrials", tokenized: false, marketCapB: 8 },
  { ticker: "009150", name: "Samsung Electro-Mechanics", sector: "Technology", tokenized: false, marketCapB: 8 },
  { ticker: "032640", name: "LG Uplus", sector: "Communication", tokenized: false, marketCapB: 5 },
  { ticker: "024110", name: "Industrial Bank of Korea", sector: "Financials", tokenized: false, marketCapB: 8 },
  { ticker: "001570", name: "Keum Kang Industrial", sector: "Materials", tokenized: false, marketCapB: 1 },
  { ticker: "377300", name: "Kakao Pay", sector: "Financials", tokenized: false, marketCapB: 5 },
  { ticker: "267250", name: "HD Hyundai Heavy Industries", sector: "Industrials", tokenized: false, marketCapB: 12 },
  { ticker: "010950", name: "S-Oil Corp.", sector: "Energy", tokenized: false, marketCapB: 6 },
  { ticker: "051900", name: "LG Household & Health Care", sector: "Consumer Staples", tokenized: false, marketCapB: 5 },
  ]
};

MARKETS["SENSEX"] = {
  name: "BSE Sensex",
  city: "Mumbai",
  country: "India",
  indexTicker: { ticker: "500325.BO", name: "S&P BSE Sensex proxy", sector: "Index", tokenized: false, marketCapB: 5 },
  constituents: [
  { ticker: "RELIANCE", name: "Reliance Industries", sector: "Energy", tokenized: false, marketCapB: 210 },
  { ticker: "TCS", name: "Tata Consultancy Services", sector: "Technology", tokenized: false, marketCapB: 160 },
  { ticker: "HDFCBANK", name: "HDFC Bank", sector: "Financials", tokenized: false, marketCapB: 150 },
  { ticker: "ICICIBANK", name: "ICICI Bank", sector: "Financials", tokenized: false, marketCapB: 100 },
  { ticker: "INFY", name: "Infosys Ltd.", sector: "Technology", tokenized: false, marketCapB: 80 },
  { ticker: "HINDUNILVR", name: "Hindustan Unilever", sector: "Consumer Staples", tokenized: false, marketCapB: 65 },
  { ticker: "ITC", name: "ITC Ltd.", sector: "Consumer Staples", tokenized: false, marketCapB: 35 },
  { ticker: "SBIN", name: "State Bank of India", sector: "Financials", tokenized: false, marketCapB: 75 },
  { ticker: "BHARTIARTL", name: "Bharti Airtel", sector: "Communication", tokenized: false, marketCapB: 120 },
  { ticker: "KOTAKBANK", name: "Kotak Mahindra Bank", sector: "Financials", tokenized: false, marketCapB: 45 },
  { ticker: "LT", name: "Larsen & Toubro", sector: "Industrials", tokenized: false, marketCapB: 50 },
  { ticker: "AXISBANK", name: "Axis Bank", sector: "Financials", tokenized: false, marketCapB: 40 },
  { ticker: "BAJFINANCE", name: "Bajaj Finance", sector: "Financials", tokenized: false, marketCapB: 55 },
  { ticker: "ASIANPAINT", name: "Asian Paints", sector: "Materials", tokenized: false, marketCapB: 30 },
  { ticker: "MARUTI", name: "Maruti Suzuki India", sector: "Consumer Disc.", tokenized: false, marketCapB: 40 },
  { ticker: "SUNPHARMA", name: "Sun Pharmaceutical", sector: "Health Care", tokenized: false, marketCapB: 45 },
  { ticker: "TITAN", name: "Titan Company", sector: "Consumer Disc.", tokenized: false, marketCapB: 35 },
  { ticker: "ULTRACEMCO", name: "UltraTech Cement", sector: "Materials", tokenized: false, marketCapB: 35 },
  { ticker: "NESTLEIND", name: "Nestle India", sector: "Consumer Staples", tokenized: false, marketCapB: 25 },
  { ticker: "WIPRO", name: "Wipro Ltd.", sector: "Technology", tokenized: false, marketCapB: 30 },
  { ticker: "HCLTECH", name: "HCL Technologies", sector: "Technology", tokenized: false, marketCapB: 45 },
  { ticker: "M&M", name: "Mahindra & Mahindra", sector: "Consumer Disc.", tokenized: false, marketCapB: 40 },
  { ticker: "POWERGRID", name: "Power Grid Corp.", sector: "Utilities", tokenized: false, marketCapB: 30 },
  { ticker: "NTPC", name: "NTPC Ltd.", sector: "Utilities", tokenized: false, marketCapB: 30 },
  { ticker: "TATASTEEL", name: "Tata Steel", sector: "Materials", tokenized: false, marketCapB: 25 },
  { ticker: "JSWSTEEL", name: "JSW Steel", sector: "Materials", tokenized: false, marketCapB: 28 },
  { ticker: "INDUSINDBK", name: "IndusInd Bank", sector: "Financials", tokenized: false, marketCapB: 15 },
  { ticker: "TECHM", name: "Tech Mahindra", sector: "Technology", tokenized: false, marketCapB: 15 },
  { ticker: "BAJAJFINSV", name: "Bajaj Finserv", sector: "Financials", tokenized: false, marketCapB: 30 },
  { ticker: "HDFCLIFE", name: "HDFC Life Insurance", sector: "Financials", tokenized: false, marketCapB: 15 },
  ]
};

MARKETS["AXJO"] = {
  name: "S&P/ASX 200",
  city: "Sydney",
  country: "Australia",
  indexTicker: { ticker: "STW.AX", name: "SPDR S&P/ASX 200 Fund", sector: "Index", tokenized: false, marketCapB: 20 },
  constituents: [
  { ticker: "BHP", name: "BHP Group", sector: "Materials", tokenized: false, marketCapB: 150 },
  { ticker: "CBA", name: "Commonwealth Bank of Australia", sector: "Financials", tokenized: false, marketCapB: 180 },
  { ticker: "CSL", name: "CSL Ltd.", sector: "Health Care", tokenized: false, marketCapB: 90 },
  { ticker: "NAB", name: "National Australia Bank", sector: "Financials", tokenized: false, marketCapB: 90 },
  { ticker: "WBC", name: "Westpac Banking Corp.", sector: "Financials", tokenized: false, marketCapB: 80 },
  { ticker: "ANZ", name: "ANZ Group Holdings", sector: "Financials", tokenized: false, marketCapB: 70 },
  { ticker: "FMG", name: "Fortescue Ltd.", sector: "Materials", tokenized: false, marketCapB: 50 },
  { ticker: "WES", name: "Wesfarmers Ltd.", sector: "Consumer Disc.", tokenized: false, marketCapB: 60 },
  { ticker: "MQG", name: "Macquarie Group", sector: "Financials", tokenized: false, marketCapB: 70 },
  { ticker: "GMG", name: "Goodman Group", sector: "Financials", tokenized: false, marketCapB: 45 },
  { ticker: "WDS", name: "Woodside Energy Group", sector: "Energy", tokenized: false, marketCapB: 35 },
  { ticker: "TLS", name: "Telstra Group", sector: "Communication", tokenized: false, marketCapB: 40 },
  { ticker: "RIO", name: "Rio Tinto (ASX)", sector: "Materials", tokenized: false, marketCapB: 40 },
  { ticker: "TCL", name: "Transurban Group", sector: "Industrials", tokenized: false, marketCapB: 35 },
  { ticker: "WOW", name: "Woolworths Group", sector: "Consumer Staples", tokenized: false, marketCapB: 35 },
  { ticker: "STO", name: "Santos Ltd.", sector: "Energy", tokenized: false, marketCapB: 20 },
  { ticker: "QBE", name: "QBE Insurance Group", sector: "Financials", tokenized: false, marketCapB: 25 },
  { ticker: "ALL", name: "Aristocrat Leisure", sector: "Consumer Disc.", tokenized: false, marketCapB: 30 },
  { ticker: "REA", name: "REA Group", sector: "Communication", tokenized: false, marketCapB: 25 },
  { ticker: "COL", name: "Coles Group", sector: "Consumer Staples", tokenized: false, marketCapB: 25 },
  { ticker: "SUN", name: "Suncorp Group", sector: "Financials", tokenized: false, marketCapB: 20 },
  { ticker: "JHX", name: "James Hardie Industries", sector: "Materials", tokenized: false, marketCapB: 20 },
  { ticker: "XRO", name: "Xero Ltd.", sector: "Technology", tokenized: false, marketCapB: 25 },
  { ticker: "IAG", name: "Insurance Australia Group", sector: "Financials", tokenized: false, marketCapB: 15 },
  { ticker: "ORG", name: "Origin Energy", sector: "Utilities", tokenized: false, marketCapB: 15 },
  { ticker: "APA", name: "APA Group", sector: "Utilities", tokenized: false, marketCapB: 12 },
  { ticker: "NST", name: "Northern Star Resources", sector: "Materials", tokenized: false, marketCapB: 18 },
  { ticker: "SHL", name: "Sonic Healthcare", sector: "Health Care", tokenized: false, marketCapB: 15 },
  { ticker: "AMC", name: "Amcor plc", sector: "Materials", tokenized: false, marketCapB: 15 },
  { ticker: "BXB", name: "Brambles Ltd.", sector: "Industrials", tokenized: false, marketCapB: 20 },
  { ticker: "QAN", name: "Qantas Airways", sector: "Industrials", tokenized: false, marketCapB: 15 },
  { ticker: "MPL", name: "Medibank Private", sector: "Financials", tokenized: false, marketCapB: 10 },
  { ticker: "COH", name: "Cochlear Ltd.", sector: "Health Care", tokenized: false, marketCapB: 18 },
  { ticker: "MIN", name: "Mineral Resources", sector: "Materials", tokenized: false, marketCapB: 8 },
  { ticker: "S32", name: "South32 Ltd.", sector: "Materials", tokenized: false, marketCapB: 12 },
  { ticker: "SCG", name: "Scentre Group", sector: "Financials", tokenized: false, marketCapB: 15 },
  { ticker: "EVN", name: "Evolution Mining", sector: "Materials", tokenized: false, marketCapB: 12 },
  { ticker: "ASX", name: "ASX Ltd.", sector: "Financials", tokenized: false, marketCapB: 12 },
  { ticker: "PLS", name: "Pilbara Minerals", sector: "Materials", tokenized: false, marketCapB: 8 },
  { ticker: "RMD", name: "ResMed Inc. (ASX)", sector: "Health Care", tokenized: false, marketCapB: 25 },
  { ticker: "NEM", name: "Newmont Corp. (ASX)", sector: "Materials", tokenized: false, marketCapB: 15 },
  ]
};

MARKETS["GSPTSE"] = {
  name: "S&P/TSX Composite",
  city: "Toronto",
  country: "Canada",
  indexTicker: { ticker: "XIC.TO", name: "iShares Core S&P/TSX Capped Composite ETF", sector: "Index", tokenized: false, marketCapB: 15 },
  constituents: [
  { ticker: "RY", name: "Royal Bank of Canada", sector: "Financials", tokenized: false, marketCapB: 180 },
  { ticker: "TD", name: "Toronto-Dominion Bank", sector: "Financials", tokenized: false, marketCapB: 120 },
  { ticker: "SHOP", name: "Shopify Inc.", sector: "Technology", tokenized: false, marketCapB: 130 },
  { ticker: "ENB", name: "Enbridge Inc.", sector: "Energy", tokenized: false, marketCapB: 90 },
  { ticker: "CNQ", name: "Canadian Natural Resources", sector: "Energy", tokenized: false, marketCapB: 70 },
  { ticker: "BN", name: "Brookfield Corp.", sector: "Financials", tokenized: false, marketCapB: 100 },
  { ticker: "BMO", name: "Bank of Montreal", sector: "Financials", tokenized: false, marketCapB: 90 },
  { ticker: "CP", name: "Canadian Pacific Kansas City", sector: "Industrials", tokenized: false, marketCapB: 80 },
  { ticker: "TRI", name: "Thomson Reuters", sector: "Industrials", tokenized: false, marketCapB: 70 },
  { ticker: "BNS", name: "Bank of Nova Scotia", sector: "Financials", tokenized: false, marketCapB: 70 },
  { ticker: "CNR", name: "Canadian National Railway", sector: "Industrials", tokenized: false, marketCapB: 70 },
  { ticker: "CM", name: "Canadian Imperial Bank of Commerce", sector: "Financials", tokenized: false, marketCapB: 60 },
  { ticker: "SU", name: "Suncor Energy", sector: "Energy", tokenized: false, marketCapB: 55 },
  { ticker: "MFC", name: "Manulife Financial", sector: "Financials", tokenized: false, marketCapB: 55 },
  { ticker: "TRP", name: "TC Energy Corp.", sector: "Energy", tokenized: false, marketCapB: 45 },
  { ticker: "ATD", name: "Alimentation Couche-Tard", sector: "Consumer Staples", tokenized: false, marketCapB: 55 },
  { ticker: "BCE", name: "BCE Inc.", sector: "Communication", tokenized: false, marketCapB: 30 },
  { ticker: "CSU", name: "Constellation Software", sector: "Technology", tokenized: false, marketCapB: 70 },
  { ticker: "WCN", name: "Waste Connections", sector: "Industrials", tokenized: false, marketCapB: 45 },
  { ticker: "GIB.A", name: "CGI Inc.", sector: "Technology", tokenized: false, marketCapB: 30 },
  { ticker: "SLF", name: "Sun Life Financial", sector: "Financials", tokenized: false, marketCapB: 35 },
  { ticker: "FNV", name: "Franco-Nevada Corp.", sector: "Materials", tokenized: false, marketCapB: 30 },
  { ticker: "AEM", name: "Agnico Eagle Mines", sector: "Materials", tokenized: false, marketCapB: 50 },
  { ticker: "NTR", name: "Nutrien Ltd.", sector: "Materials", tokenized: false, marketCapB: 25 },
  { ticker: "POW", name: "Power Corp. of Canada", sector: "Financials", tokenized: false, marketCapB: 25 },
  { ticker: "IMO", name: "Imperial Oil", sector: "Energy", tokenized: false, marketCapB: 35 },
  { ticker: "WPM", name: "Wheaton Precious Metals", sector: "Materials", tokenized: false, marketCapB: 35 },
  { ticker: "FTS", name: "Fortis Inc.", sector: "Utilities", tokenized: false, marketCapB: 30 },
  { ticker: "L", name: "Loblaw Companies", sector: "Consumer Staples", tokenized: false, marketCapB: 40 },
  { ticker: "QSR", name: "Restaurant Brands International", sector: "Consumer Disc.", tokenized: false, marketCapB: 20 },
  { ticker: "GIL", name: "Gildan Activewear", sector: "Consumer Disc.", tokenized: false, marketCapB: 8 },
  { ticker: "DOL", name: "Dollarama Inc.", sector: "Consumer Disc.", tokenized: false, marketCapB: 30 },
  { ticker: "K", name: "Kinross Gold", sector: "Materials", tokenized: false, marketCapB: 15 },
  { ticker: "MG", name: "Magna International", sector: "Consumer Disc.", tokenized: false, marketCapB: 10 },
  { ticker: "CCO", name: "Cameco Corp.", sector: "Energy", tokenized: false, marketCapB: 25 },
  { ticker: "OTEX", name: "Open Text Corp.", sector: "Technology", tokenized: false, marketCapB: 8 },
  { ticker: "EMA", name: "Emera Inc.", sector: "Utilities", tokenized: false, marketCapB: 12 },
  { ticker: "H", name: "Hydro One Ltd.", sector: "Utilities", tokenized: false, marketCapB: 20 },
  { ticker: "PPL", name: "Pembina Pipeline", sector: "Energy", tokenized: false, marketCapB: 20 },
  { ticker: "CTC.A", name: "Canadian Tire Corp.", sector: "Consumer Disc.", tokenized: false, marketCapB: 8 },
  { ticker: "WN", name: "George Weston Ltd.", sector: "Consumer Staples", tokenized: false, marketCapB: 25 },
  { ticker: "IFC", name: "Intact Financial Corp.", sector: "Financials", tokenized: false, marketCapB: 30 },
  { ticker: "TIH", name: "Toromont Industries", sector: "Industrials", tokenized: false, marketCapB: 8 },
  { ticker: "KEY", name: "Keyera Corp.", sector: "Energy", tokenized: false, marketCapB: 7 },
  ]
};

MARKETS["BVSP"] = {
  name: "Ibovespa",
  city: "Sao Paulo",
  country: "Brazil",
  indexTicker: { ticker: "BOVA11.SA", name: "iShares Ibovespa Fundo de Indice", sector: "Index", tokenized: false, marketCapB: 10 },
  constituents: [
  { ticker: "PETR4", name: "Petrobras", sector: "Energy", tokenized: false, marketCapB: 90 },
  { ticker: "VALE3", name: "Vale SA", sector: "Materials", tokenized: false, marketCapB: 60 },
  { ticker: "ITUB4", name: "Itau Unibanco Holding", sector: "Financials", tokenized: false, marketCapB: 60 },
  { ticker: "BBDC4", name: "Banco Bradesco", sector: "Financials", tokenized: false, marketCapB: 30 },
  { ticker: "ABEV3", name: "Ambev SA", sector: "Consumer Staples", tokenized: false, marketCapB: 30 },
  { ticker: "B3SA3", name: "B3 SA (Bolsa)", sector: "Financials", tokenized: false, marketCapB: 15 },
  { ticker: "WEGE3", name: "WEG SA", sector: "Industrials", tokenized: false, marketCapB: 25 },
  { ticker: "BBAS3", name: "Banco do Brasil", sector: "Financials", tokenized: false, marketCapB: 25 },
  { ticker: "RENT3", name: "Localiza Rent a Car", sector: "Industrials", tokenized: false, marketCapB: 10 },
  { ticker: "SUZB3", name: "Suzano SA", sector: "Materials", tokenized: false, marketCapB: 15 },
  { ticker: "ITSA4", name: "Itausa SA", sector: "Financials", tokenized: false, marketCapB: 15 },
  { ticker: "PRIO3", name: "PetroRio SA", sector: "Energy", tokenized: false, marketCapB: 8 },
  { ticker: "RAIL3", name: "Rumo SA", sector: "Industrials", tokenized: false, marketCapB: 8 },
  { ticker: "JBSS3", name: "JBS SA", sector: "Consumer Staples", tokenized: false, marketCapB: 15 },
  { ticker: "EQTL3", name: "Equatorial Energia", sector: "Utilities", tokenized: false, marketCapB: 10 },
  { ticker: "RADL3", name: "Raia Drogasil", sector: "Consumer Staples", tokenized: false, marketCapB: 10 },
  { ticker: "GGBR4", name: "Gerdau SA", sector: "Materials", tokenized: false, marketCapB: 8 },
  { ticker: "VIVT3", name: "Telefonica Brasil", sector: "Communication", tokenized: false, marketCapB: 10 },
  { ticker: "ELET3", name: "Eletrobras", sector: "Utilities", tokenized: false, marketCapB: 15 },
  { ticker: "HAPV3", name: "Hapvida", sector: "Health Care", tokenized: false, marketCapB: 8 },
  { ticker: "CSNA3", name: "Companhia Siderurgica Nacional", sector: "Materials", tokenized: false, marketCapB: 5 },
  { ticker: "CSAN3", name: "Cosan SA", sector: "Energy", tokenized: false, marketCapB: 5 },
  { ticker: "SBSP3", name: "Sabesp", sector: "Utilities", tokenized: false, marketCapB: 10 },
  { ticker: "UGPA3", name: "Ultrapar Participacoes", sector: "Energy", tokenized: false, marketCapB: 5 },
  { ticker: "CMIG4", name: "Cemig", sector: "Utilities", tokenized: false, marketCapB: 8 },
  { ticker: "BPAC11", name: "BTG Pactual", sector: "Financials", tokenized: false, marketCapB: 20 },
  { ticker: "TOTS3", name: "Totvs SA", sector: "Technology", tokenized: false, marketCapB: 5 },
  { ticker: "EMBR3", name: "Embraer SA", sector: "Industrials", tokenized: false, marketCapB: 10 },
  { ticker: "CPFE3", name: "CPFL Energia", sector: "Utilities", tokenized: false, marketCapB: 8 },
  { ticker: "MGLU3", name: "Magazine Luiza", sector: "Consumer Disc.", tokenized: false, marketCapB: 3 },
  { ticker: "NTCO3", name: "Natura &Co", sector: "Consumer Staples", tokenized: false, marketCapB: 3 },
  { ticker: "LREN3", name: "Lojas Renner", sector: "Consumer Disc.", tokenized: false, marketCapB: 4 },
  { ticker: "CYRE3", name: "Cyrela Brazil Realty", sector: "Financials", tokenized: false, marketCapB: 3 },
  { ticker: "BRFS3", name: "BRF SA", sector: "Consumer Staples", tokenized: false, marketCapB: 5 },
  { ticker: "KLBN11", name: "Klabin SA", sector: "Materials", tokenized: false, marketCapB: 6 },
  { ticker: "YDUQ3", name: "YDUQS Participacoes", sector: "Consumer Disc.", tokenized: false, marketCapB: 2 },
  ]
};

MARKETS["IBEX"] = {
  name: "IBEX 35",
  city: "Madrid",
  country: "Spain",
  indexTicker: { ticker: "IBEX35.MC", name: "Amundi IBEX 35 UCITS ETF", sector: "Index", tokenized: false, marketCapB: 15 },
  constituents: [
  { ticker: "ITX", name: "Inditex SA", sector: "Consumer Disc.", tokenized: false, marketCapB: 150 },
  { ticker: "SAN", name: "Banco Santander", sector: "Financials", tokenized: false, marketCapB: 90 },
  { ticker: "BBVA", name: "BBVA", sector: "Financials", tokenized: false, marketCapB: 70 },
  { ticker: "IBE", name: "Iberdrola SA", sector: "Utilities", tokenized: false, marketCapB: 90 },
  { ticker: "CABK", name: "CaixaBank SA", sector: "Financials", tokenized: false, marketCapB: 45 },
  { ticker: "REP", name: "Repsol SA", sector: "Energy", tokenized: false, marketCapB: 20 },
  { ticker: "AMS", name: "Amadeus IT Group", sector: "Technology", tokenized: false, marketCapB: 30 },
  { ticker: "TEF", name: "Telefonica SA", sector: "Communication", tokenized: false, marketCapB: 25 },
  { ticker: "FER", name: "Ferrovial SE", sector: "Industrials", tokenized: false, marketCapB: 30 },
  { ticker: "ELE", name: "Endesa SA", sector: "Utilities", tokenized: false, marketCapB: 25 },
  { ticker: "NTGY", name: "Naturgy Energy Group", sector: "Utilities", tokenized: false, marketCapB: 25 },
  { ticker: "AENA", name: "Aena SME", sector: "Industrials", tokenized: false, marketCapB: 30 },
  { ticker: "ANA", name: "Acciona SA", sector: "Utilities", tokenized: false, marketCapB: 8 },
  { ticker: "MAP", name: "Mapfre SA", sector: "Financials", tokenized: false, marketCapB: 8 },
  { ticker: "SAB", name: "Banco de Sabadell", sector: "Financials", tokenized: false, marketCapB: 15 },
  { ticker: "BKT", name: "Bankinter SA", sector: "Financials", tokenized: false, marketCapB: 8 },
  { ticker: "MEL", name: "Melia Hotels International", sector: "Consumer Disc.", tokenized: false, marketCapB: 2 },
  { ticker: "GRF", name: "Grifols SA", sector: "Health Care", tokenized: false, marketCapB: 6 },
  { ticker: "COL", name: "Inmobiliaria Colonial", sector: "Financials", tokenized: false, marketCapB: 3 },
  { ticker: "ACS", name: "ACS Actividades de Construccion", sector: "Industrials", tokenized: false, marketCapB: 10 },
  { ticker: "FDR", name: "Fluidra SA", sector: "Industrials", tokenized: false, marketCapB: 3 },
  { ticker: "IDR", name: "Indra Sistemas", sector: "Technology", tokenized: false, marketCapB: 4 },
  { ticker: "RED", name: "Redeia Corp.", sector: "Utilities", tokenized: false, marketCapB: 10 },
  { ticker: "ENG", name: "Enagas SA", sector: "Utilities", tokenized: false, marketCapB: 5 },
  { ticker: "SLR", name: "Solaria Energia", sector: "Utilities", tokenized: false, marketCapB: 1 },
  { ticker: "CLNX", name: "Cellnex Telecom", sector: "Communication", tokenized: false, marketCapB: 25 },
  { ticker: "PUIG", name: "Puig Brands", sector: "Consumer Disc.", tokenized: false, marketCapB: 12 },
  { ticker: "UNI", name: "Unicaja Banco", sector: "Financials", tokenized: false, marketCapB: 5 },
  { ticker: "LOG", name: "Logista SA", sector: "Industrials", tokenized: false, marketCapB: 3 },
  { ticker: "ROVI", name: "Laboratorios Rovi", sector: "Health Care", tokenized: false, marketCapB: 3 },
  { ticker: "VIS", name: "Viscofan SA", sector: "Consumer Staples", tokenized: false, marketCapB: 3 },
  { ticker: "ANE", name: "Acciona Energia", sector: "Utilities", tokenized: false, marketCapB: 8 },
  ]
};

MARKETS["FTSEMIB"] = {
  name: "FTSE MIB",
  city: "Milan",
  country: "Italy",
  indexTicker: { ticker: "EWI", name: "iShares MSCI Italy ETF", sector: "Index", tokenized: false, marketCapB: 20 },
  constituents: [
  { ticker: "ENI", name: "Eni SpA", sector: "Energy", tokenized: false, marketCapB: 50 },
  { ticker: "ISP", name: "Intesa Sanpaolo", sector: "Financials", tokenized: false, marketCapB: 90 },
  { ticker: "UCG", name: "UniCredit SpA", sector: "Financials", tokenized: false, marketCapB: 90 },
  { ticker: "ENEL", name: "Enel SpA", sector: "Utilities", tokenized: false, marketCapB: 80 },
  { ticker: "G", name: "Assicurazioni Generali", sector: "Financials", tokenized: false, marketCapB: 45 },
  { ticker: "RACE", name: "Ferrari NV", sector: "Consumer Disc.", tokenized: false, marketCapB: 90 },
  { ticker: "STLAM", name: "Stellantis NV", sector: "Consumer Disc.", tokenized: false, marketCapB: 30 },
  { ticker: "SRG", name: "Snam SpA", sector: "Utilities", tokenized: false, marketCapB: 15 },
  { ticker: "TRN", name: "Terna SpA", sector: "Utilities", tokenized: false, marketCapB: 20 },
  { ticker: "PST", name: "Poste Italiane", sector: "Financials", tokenized: false, marketCapB: 15 },
  { ticker: "MB", name: "Mediobanca", sector: "Financials", tokenized: false, marketCapB: 12 },
  { ticker: "BAMI", name: "Banco BPM", sector: "Financials", tokenized: false, marketCapB: 12 },
  { ticker: "BMPS", name: "Banca Monte dei Paschi", sector: "Financials", tokenized: false, marketCapB: 8 },
  { ticker: "A2A", name: "A2A SpA", sector: "Utilities", tokenized: false, marketCapB: 8 },
  { ticker: "MONC", name: "Moncler SpA", sector: "Consumer Disc.", tokenized: false, marketCapB: 15 },
  { ticker: "PRY", name: "Prysmian SpA", sector: "Industrials", tokenized: false, marketCapB: 12 },
  { ticker: "REC", name: "Recordati SpA", sector: "Health Care", tokenized: false, marketCapB: 12 },
  { ticker: "CPR", name: "Davide Campari-Milano", sector: "Consumer Staples", tokenized: false, marketCapB: 8 },
  { ticker: "TIT", name: "Telecom Italia", sector: "Communication", tokenized: false, marketCapB: 8 },
  { ticker: "AMP", name: "Amplifon SpA", sector: "Health Care", tokenized: false, marketCapB: 6 },
  { ticker: "BPE", name: "BPER Banca", sector: "Financials", tokenized: false, marketCapB: 8 },
  { ticker: "IP", name: "Interpump Group", sector: "Industrials", tokenized: false, marketCapB: 4 },
  { ticker: "BGN", name: "Banca Generali", sector: "Financials", tokenized: false, marketCapB: 5 },
  { ticker: "FBK", name: "FinecoBank", sector: "Financials", tokenized: false, marketCapB: 12 },
  { ticker: "HER", name: "Hera SpA", sector: "Utilities", tokenized: false, marketCapB: 5 },
  { ticker: "IG", name: "Italgas SpA", sector: "Utilities", tokenized: false, marketCapB: 5 },
  { ticker: "LDO", name: "Leonardo SpA", sector: "Industrials", tokenized: false, marketCapB: 15 },
  { ticker: "NEXI", name: "Nexi SpA", sector: "Technology", tokenized: false, marketCapB: 8 },
  { ticker: "PIRC", name: "Pirelli & C. SpA", sector: "Consumer Disc.", tokenized: false, marketCapB: 5 },
  { ticker: "SPM", name: "Saipem SpA", sector: "Energy", tokenized: false, marketCapB: 4 },
  { ticker: "STMMI", name: "STMicroelectronics (MI)", sector: "Technology", tokenized: false, marketCapB: 25 },
  { ticker: "UNI.MI", name: "Unipol Gruppo", sector: "Financials", tokenized: false, marketCapB: 6 },
  { ticker: "DIA.MI", name: "Diasorin SpA", sector: "Health Care", tokenized: false, marketCapB: 5 },
  { ticker: "INW", name: "Inwit SpA", sector: "Communication", tokenized: false, marketCapB: 8 },
  { ticker: "BRE", name: "Brembo SpA", sector: "Consumer Disc.", tokenized: false, marketCapB: 2 },
  { ticker: "TEN", name: "Tenaris SA (MI)", sector: "Energy", tokenized: false, marketCapB: 20 },
  ]
};

MARKETS["SMI"] = {
  name: "Swiss Market Index",
  city: "Zurich",
  country: "Switzerland",
  indexTicker: { ticker: "CSSMI.SW", name: "iShares SMI ETF", sector: "Index", tokenized: false, marketCapB: 15 },
  constituents: [
  { ticker: "NESN", name: "Nestle SA", sector: "Consumer Staples", tokenized: false, marketCapB: 260 },
  { ticker: "ROG", name: "Roche Holding", sector: "Health Care", tokenized: false, marketCapB: 230 },
  { ticker: "NOVN", name: "Novartis AG", sector: "Health Care", tokenized: false, marketCapB: 200 },
  { ticker: "UBSG", name: "UBS Group", sector: "Financials", tokenized: false, marketCapB: 90 },
  { ticker: "ZURN", name: "Zurich Insurance Group", sector: "Financials", tokenized: false, marketCapB: 90 },
  { ticker: "ABBN", name: "ABB Ltd.", sector: "Industrials", tokenized: false, marketCapB: 110 },
  { ticker: "CFR", name: "Compagnie Financiere Richemont", sector: "Consumer Disc.", tokenized: false, marketCapB: 90 },
  { ticker: "SIKA", name: "Sika AG", sector: "Materials", tokenized: false, marketCapB: 40 },
  { ticker: "LONN", name: "Lonza Group", sector: "Health Care", tokenized: false, marketCapB: 35 },
  { ticker: "GIVN", name: "Givaudan SA", sector: "Materials", tokenized: false, marketCapB: 35 },
  { ticker: "HOLN", name: "Holcim AG", sector: "Materials", tokenized: false, marketCapB: 65 },
  { ticker: "SREN", name: "Swiss Re AG", sector: "Financials", tokenized: false, marketCapB: 35 },
  { ticker: "ALC", name: "Alcon Inc.", sector: "Health Care", tokenized: false, marketCapB: 45 },
  { ticker: "SCMN", name: "Swisscom AG", sector: "Communication", tokenized: false, marketCapB: 25 },
  { ticker: "GEBN", name: "Geberit AG", sector: "Industrials", tokenized: false, marketCapB: 22 },
  { ticker: "SLHN", name: "Swiss Life Holding", sector: "Financials", tokenized: false, marketCapB: 20 },
  { ticker: "PGHN", name: "Partners Group Holding", sector: "Financials", tokenized: false, marketCapB: 25 },
  { ticker: "KNIN", name: "Kuehne+Nagel International", sector: "Industrials", tokenized: false, marketCapB: 18 },
  { ticker: "LOGN", name: "Logitech International", sector: "Technology", tokenized: false, marketCapB: 15 },
  { ticker: "SOON", name: "Sonova Holding", sector: "Health Care", tokenized: false, marketCapB: 18 },
  ]
};

MARKETS["STI"] = {
  name: "Straits Times Index",
  city: "Singapore",
  country: "Singapore",
  indexTicker: { ticker: "ES3.SI", name: "SPDR STI ETF", sector: "Index", tokenized: false, marketCapB: 5 },
  constituents: [
  { ticker: "D05", name: "DBS Group Holdings", sector: "Financials", tokenized: false, marketCapB: 70 },
  { ticker: "O39", name: "OCBC Bank", sector: "Financials", tokenized: false, marketCapB: 55 },
  { ticker: "U11", name: "United Overseas Bank", sector: "Financials", tokenized: false, marketCapB: 45 },
  { ticker: "C6L", name: "Singapore Airlines", sector: "Industrials", tokenized: false, marketCapB: 15 },
  { ticker: "Z74", name: "Singtel", sector: "Communication", tokenized: false, marketCapB: 45 },
  { ticker: "S68", name: "Singapore Exchange", sector: "Financials", tokenized: false, marketCapB: 10 },
  { ticker: "S63", name: "ST Engineering", sector: "Industrials", tokenized: false, marketCapB: 15 },
  { ticker: "C38U", name: "CapitaLand Integrated Commercial Trust", sector: "Financials", tokenized: false, marketCapB: 12 },
  { ticker: "A17U", name: "CapitaLand Ascendas REIT", sector: "Financials", tokenized: false, marketCapB: 10 },
  { ticker: "C09", name: "City Developments", sector: "Financials", tokenized: false, marketCapB: 4 },
  { ticker: "BN4", name: "Keppel Corp.", sector: "Industrials", tokenized: false, marketCapB: 10 },
  { ticker: "U96", name: "Sembcorp Industries", sector: "Utilities", tokenized: false, marketCapB: 8 },
  { ticker: "F34", name: "Wilmar International", sector: "Consumer Staples", tokenized: false, marketCapB: 15 },
  { ticker: "G13", name: "Genting Singapore", sector: "Consumer Disc.", tokenized: false, marketCapB: 6 },
  { ticker: "Y92", name: "Thai Beverage", sector: "Consumer Staples", tokenized: false, marketCapB: 8 },
  { ticker: "V03", name: "Venture Corp.", sector: "Technology", tokenized: false, marketCapB: 3 },
  { ticker: "C31", name: "CapitaLand Investment", sector: "Financials", tokenized: false, marketCapB: 12 },
  { ticker: "J36", name: "Jardine Matheson Holdings", sector: "Industrials", tokenized: false, marketCapB: 15 },
  { ticker: "N2IU", name: "Mapletree Logistics Trust", sector: "Financials", tokenized: false, marketCapB: 5 },
  { ticker: "ME8U", name: "Mapletree Industrial Trust", sector: "Financials", tokenized: false, marketCapB: 4 },
  { ticker: "H78", name: "Hongkong Land Holdings", sector: "Financials", tokenized: false, marketCapB: 10 },
  { ticker: "D01", name: "Dairy Farm Intl. (DFI Retail Group)", sector: "Consumer Staples", tokenized: false, marketCapB: 3 },
  { ticker: "BS6", name: "Yangzijiang Shipbuilding", sector: "Industrials", tokenized: false, marketCapB: 8 },
  { ticker: "U14", name: "UOL Group", sector: "Financials", tokenized: false, marketCapB: 4 },
  { ticker: "5CP", name: "Seatrium Ltd.", sector: "Industrials", tokenized: false, marketCapB: 4 },
  { ticker: "C52", name: "ComfortDelGro Corp.", sector: "Industrials", tokenized: false, marketCapB: 3 },
  { ticker: "M44U", name: "Mapletree Pan Asia Commercial Trust", sector: "Financials", tokenized: false, marketCapB: 5 },
  { ticker: "EMI", name: "Emperador Inc.", sector: "Consumer Staples", tokenized: false, marketCapB: 2 },
  ]
};

MARKETS["TWII"] = {
  name: "TAIEX",
  city: "Taipei",
  country: "Taiwan",
  indexTicker: { ticker: "0050.TW", name: "Yuanta/P-shares Taiwan Top 50 ETF", sector: "Index", tokenized: false, marketCapB: 20 },
  constituents: [
  { ticker: "2330", name: "Taiwan Semiconductor Mfg. (TSMC)", sector: "Technology", tokenized: false, marketCapB: 900 },
  { ticker: "2454", name: "MediaTek Inc.", sector: "Technology", tokenized: false, marketCapB: 60 },
  { ticker: "2317", name: "Hon Hai Precision (Foxconn)", sector: "Technology", tokenized: false, marketCapB: 80 },
  { ticker: "2308", name: "Delta Electronics", sector: "Technology", tokenized: false, marketCapB: 30 },
  { ticker: "2382", name: "Quanta Computer", sector: "Technology", tokenized: false, marketCapB: 25 },
  { ticker: "2412", name: "Chunghwa Telecom", sector: "Communication", tokenized: false, marketCapB: 30 },
  { ticker: "2881", name: "Fubon Financial Holding", sector: "Financials", tokenized: false, marketCapB: 30 },
  { ticker: "2882", name: "Cathay Financial Holding", sector: "Financials", tokenized: false, marketCapB: 25 },
  { ticker: "2891", name: "CTBC Financial Holding", sector: "Financials", tokenized: false, marketCapB: 20 },
  { ticker: "1301", name: "Formosa Plastics", sector: "Materials", tokenized: false, marketCapB: 15 },
  { ticker: "1303", name: "Nan Ya Plastics", sector: "Materials", tokenized: false, marketCapB: 12 },
  { ticker: "2002", name: "China Steel Corp.", sector: "Materials", tokenized: false, marketCapB: 10 },
  { ticker: "3711", name: "ASE Technology Holding", sector: "Technology", tokenized: false, marketCapB: 25 },
  { ticker: "2379", name: "Realtek Semiconductor", sector: "Technology", tokenized: false, marketCapB: 15 },
  { ticker: "2303", name: "United Microelectronics (UMC)", sector: "Technology", tokenized: false, marketCapB: 20 },
  { ticker: "1216", name: "Uni-President Enterprises", sector: "Consumer Staples", tokenized: false, marketCapB: 12 },
  { ticker: "2886", name: "Mega Financial Holding", sector: "Financials", tokenized: false, marketCapB: 15 },
  { ticker: "2892", name: "First Financial Holding", sector: "Financials", tokenized: false, marketCapB: 10 },
  { ticker: "5871", name: "Chailease Holding", sector: "Financials", tokenized: false, marketCapB: 12 },
  { ticker: "2409", name: "AU Optronics", sector: "Technology", tokenized: false, marketCapB: 5 },
  { ticker: "3045", name: "Taiwan Mobile", sector: "Communication", tokenized: false, marketCapB: 12 },
  { ticker: "2880", name: "Hua Nan Financial Holding", sector: "Financials", tokenized: false, marketCapB: 8 },
  { ticker: "2884", name: "E.Sun Financial Holding", sector: "Financials", tokenized: false, marketCapB: 10 },
  { ticker: "2885", name: "Yuanta Financial Holding", sector: "Financials", tokenized: false, marketCapB: 8 },
  { ticker: "9910", name: "Feng Tay Enterprise", sector: "Consumer Disc.", tokenized: false, marketCapB: 4 },
  { ticker: "1101", name: "Taiwan Cement", sector: "Materials", tokenized: false, marketCapB: 6 },
  { ticker: "2207", name: "Hotai Motor", sector: "Consumer Disc.", tokenized: false, marketCapB: 8 },
  { ticker: "2327", name: "Yageo Corp.", sector: "Technology", tokenized: false, marketCapB: 8 },
  { ticker: "6505", name: "Formosa Petrochemical", sector: "Energy", tokenized: false, marketCapB: 15 },
  { ticker: "3034", name: "Novatek Microelectronics", sector: "Technology", tokenized: false, marketCapB: 15 },
  ]
};


/* ---------------- generalized accessors ---------------- */
function getMarketIds() {
  return Object.keys(MARKETS);
}
function getMarket(marketId) {
  return MARKETS[marketId] || null;
}
function getMarketUniverse(marketId) {
  const m = getMarket(marketId);
  if (!m) return [];
  return [m.indexTicker, ...m.constituents];
}
function getMarketTickerData(marketId, ticker) {
  return getMarketUniverse(marketId).find(t => t.ticker === ticker.toUpperCase());
}
function getMarketSectors(marketId) {
  const m = getMarket(marketId);
  if (!m) return [];
  const seen = new Set();
  const order = [];
  for (const t of m.constituents) {
    if (!seen.has(t.sector)) { seen.add(t.sector); order.push(t.sector); }
  }
  return order;
}
